var district = [
    {
      id: 1,
      state_id: '17',
      code: 'MMR017D002',
      name: 'ဟင်္သာတခရိုင်',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    
    },
    {
      id: 2,
      state_id: '17',
      code: 'MMR017D004',
      name: 'လပွတ္တာခရိုင်',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 3,
      state_id: '17',
      code: 'MMR017D005',
      name: 'မအူပင်ခရိုင်',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 4,
      state_id: '17',
      code: 'MMR017D003',
      name: 'မြောင်းမြခရိုင်',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 5,
      state_id: '17',
      code: 'MMR017D001',
      name: 'ပုသိမ်ခရိုင်',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 6,
      state_id: '17',
      code: 'MMR017D006',
      name: 'ဖျာပုံခရိုင်',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 7,
      state_id: '7',
      code: 'MMR007D001',
      name: 'ပဲခူးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 8,
      state_id: '7',
      code: 'MMR007D002',
      name: 'တောင်ငူခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 9,
      state_id: '8',
      code: 'MMR008D001',
      name: 'ပြည်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 10,
      state_id: '8',
      code: 'MMR008D002',
      name: 'သာယာဝတီခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 11,
      state_id: '4',
      code: 'MMR004D001',
      name: 'ဖလန်းခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 12,
      state_id: '4',
      code: 'MMR004D003',
      name: 'ဟားခါးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 13,
      state_id: '4',
      code: 'MMR004D002',
      name: 'မင်းတပ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 14,
      state_id: '1',
      code: 'MMR001D003',
      name: 'ဗန်းမော်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 15,
      state_id: '1',
      code: 'MMR001D002',
      name: 'မိုးညှင်းခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 16,
      state_id: '1',
      code: 'MMR001D001',
      name: 'မြစ်ကြီးနားခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 17,
      state_id: '1',
      code: 'MMR001D004',
      name: 'ပူတာအိုခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 18,
      state_id: '2',
      code: 'MMR002D002',
      name: 'ဘောလခဲခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 19,
      state_id: '2',
      code: 'MMR002D001',
      name: 'လွိုင်ကော်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 20,
      state_id: '3',
      code: 'MMR003D001',
      name: 'ဘားအံခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 21,
      state_id: '3',
      code: 'MMR003D004',
      name: 'ဖာပွန်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 22,
      state_id: '3',
      code: 'MMR003D003',
      name: 'ကော့ကရိတ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 23,
      state_id: '3',
      code: 'MMR003D002',
      name: 'မြဝတီခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 24,
      state_id: '9',
      code: 'MMR009D005',
      name: 'ဂန့်ဂေါခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 25,
      state_id: '9',
      code: 'MMR009D001',
      name: 'မကွေးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 26,
      state_id: '9',
      code: 'MMR009D002',
      name: 'မင်းဘူးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 27,
      state_id: '9',
      code: 'MMR009D004',
      name: 'ပခုက္ကူခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 28,
      state_id: '9',
      code: 'MMR009D003',
      name: 'သရက်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 29,
      state_id: '10',
      code: 'MMR010D003',
      name: 'ကျောက်ဆည်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 30,
      state_id: '10',
      code: 'MMR010D001',
      name: 'မန္တလေးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 31,
      state_id: '10',
      code: 'MMR010D007',
      name: 'မိတ္ထီလာခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 32,
      state_id: '10',
      code: 'MMR010D004',
      name: 'မြင်းခြံခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 33,
      state_id: '10',
      code: 'MMR010D005',
      name: 'ညောင်ဦးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 34,
      state_id: '10',
      code: 'MMR010D002',
      name: 'ပြင်ဦးလွင်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 35,
      state_id: '10',
      code: 'MMR010D006',
      name: 'ရမည်းသင်းခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 36,
      state_id: '11',
      code: 'MMR011D001',
      name: 'မော်လမြိုင်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 37,
      state_id: '11',
      code: 'MMR011D002',
      name: 'သထုံခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 38,
      state_id: '18',
      code: 'MMR018D002',
      name: 'ဒက္ခိဏခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 39,
      state_id: '18',
      code: 'MMR018D001',
      name: 'ဥတ္တရခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 40,
      state_id: '12',
      code: 'MMR012D003',
      name: 'ကျောက်ဖြူခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 41,
      state_id: '12',
      code: 'MMR012D002',
      name: 'မောင်တောခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 42,
      state_id: '12',
      code: 'MMR012D005',
      name: 'မြောက်ဦးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 43,
      state_id: '12',
      code: 'MMR012D001',
      name: 'စစ်တွေခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 44,
      state_id: '12',
      code: 'MMR012D004',
      name: 'သံတွဲခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 45,
      state_id: '5',
      code: 'MMR005D008',
      name: 'ခန္တီးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 46,
      state_id: '5',
      code: 'MMR005D005',
      name: 'ကလေးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 47,
      state_id: '5',
      code: 'MMR005D010',
      name: 'ကန့်ဘလူခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 48,
      state_id: '5',
      code: 'MMR005D004',
      name: 'ကသာခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 49,
      state_id: '5',
      code: 'MMR005D007',
      name: 'မော်လိုက်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 50,
      state_id: '5',
      code: 'MMR005D003',
      name: 'မုံရွာခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 51,
      state_id: '5',
      code: 'MMR005D001',
      name: 'စစ်ကိုင်းခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 52,
      state_id: '5',
      code: 'MMR005D002',
      name: 'ရွှေဘိုခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 53,
      state_id: '5',
      code: 'MMR005D006',
      name: 'တမူးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 54,
      state_id: '5',
      code: 'MMR005D009',
      name: 'ယင်းမာပင်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 55,
      state_id: '16',
      code: 'MMR016D001',
      name: 'ကျိုင်းတုံခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 56,
      state_id: '16',
      code: 'MMR016D333',
      name: 'မိုင်းပေါက်-ဝအထူးဒေသ (၂)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 57,
      state_id: '16',
      code: 'MMR016D004',
      name: 'မိုင်းဖြတ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 58,
      state_id: '16',
      code: 'MMR016D002',
      name: 'မိုင်းဆတ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 59,
      state_id: '16',
      code: 'MMR016D003',
      name: 'တာချီလိတ်ခရိုင်  ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 60,
      state_id: '15',
      code: 'MMR015D006',
      name: 'ဟိုပန်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 61,
      state_id: '15',
      code: 'MMR015D004',
      name: 'ကွမ်းလုံခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 62,
      state_id: '15',
      code: 'MMR015D003',
      name: 'ကျောက်မဲခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 63,
      state_id: '15',
      code: 'MMR015D001',
      name: 'လားရှိုးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 64,
      state_id: '15',
      code: 'MMR015D005',
      name: 'လောက်ကိုင်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 65,
      state_id: '15',
      code: 'MMR015D221',
      name: 'လောက်ကိုင်-ကိုးကန့်အထူးဒေသ (၁)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 66,
      state_id: '15',
      code: 'MMR015D007',
      name: 'မက်မန်းခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
  
    {
      id: 67,
      state_id: '15',
      code: 'MMR015D331',
      name: 'မိုင်းမော-ဝအထူးဒေသ (၂)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 68,
      state_id: '15',
      code: 'MMR015D008',
      name: 'မိုးမိတ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 69,
      state_id: '15',
      code: 'MMR015D002',
      name: 'မူဆယ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 70,
      state_id: '15',
      code: 'MMR015D332',
      name: 'ဝိန်းကောင်-ဝအထူးဒေသ (၂)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 71,
      state_id: '14',
      code: 'MMR014D003',
      name: 'လင်းခေးရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 72,
      state_id: '14',
      code: 'MMR014D002',
      name: 'လွိုင်လင်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 73,
      state_id: '14',
      code: 'MMR014D001',
      name: 'တောင်ကြီးခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 74,
      state_id: '06',
      code: 'MMR006D001',
      name: 'ထားဝယ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 75,
      state_id: '06',
      code: 'MMR006D003',
      name: 'တကော့သောင်းခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 76,
      state_id: '06',
      code: 'MMR006D002',
      name: 'မြိတ်ခရိုင်    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 77,
      state_id: '13',
      code: 'MMR013D002',
      name: 'ရန်ကုန်(အရှေ့ပိုင်း)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 78,
      state_id: '13',
      code: 'MMR013D001',
      name: 'ရန်ကုန်(မြောက်ပိုင်း)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 79,
      state_id: '13',
      code: 'MMR013D003',
      name: 'ရန်ကုန်(တောင်ပိုင်း)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
    {
      id: 80,
      state_id: '13',
      code: 'MMR013D004',
      name: 'ရန်ကုန်(အနောက်ပိုင်း)    ',
      created_by: 'admin',
      updated_by: 'admin',
      status: 'ACTIVE',
    },
  
  ]